//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int ReservacionId { get; set; }
        public int VueloId { get; set; }
        public int TransaccionId { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
