//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelo()
        {
            this.Reservacion = new HashSet<Reservacion>();
        }
    
        public int VueloId { get; set; }
        public int LugarOrigenId { get; set; }
        public int LugarDestinoId { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public int NumeroPasajeros { get; set; }
        public decimal Precio { get; set; }
        public Nullable<bool> VisaNecesitada { get; set; }
        public Nullable<bool> Habilitado { get; set; }
    
        public virtual Lugar Lugar { get; set; }
        public virtual Lugar Lugar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservacion> Reservacion { get; set; }
    }
}
